<?xml version="1.0" encoding="utf-8"?><Database Name="ProjetBD" Class="LoginDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-DUS1CLA\SQLEXPRESS;Initial Catalog=ProjetBD;Integrated Security=True" SettingsObjectName="TelerikWpfApp1.Properties.Settings" SettingsPropertyName="ProjetBDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.login" Member="login">
    <Type Name="login">
      <Column Name="username" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="pass" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </Type>
  </Table>
</Database>